language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e "
        using Pkg;
        Pkg.clone(pwd(), \"Libtask\");
        Pkg.build(\"Libtask\");
        Pkg.test(\"Libtask\"; coverage=true)
      "
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Libtask")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
