name = "Libtask"
uuid = "6f1fad26-d15e-5dc8-ae53-837a1d7b8c9f"
license = "MIT"
desc = "C shim for task copying in Turing"
repo = "https://github.com/TuringLang/Libtask.jl.git"
version = "0.5.0"

[deps]
Libtask_jll = "3ae2931a-708c-5973-9c38-ccf7496fb450"

[compat]
Libtask_jll = "0.3.2"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
