name: MemLayout Info Generating
on:
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        version:
          - '1.3.1'
          - '1.4.2'
          - '1.5.3'
          - '1.5.4'
          - '1.6.1'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        arch:
          - x64
          - x86
        exclude:
          - os: macOS-latest
            arch: x86
    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: i686
          cc: 1
        if: ${{ matrix.os == 'windows-latest' && matrix.arch == 'x86' }}
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - run: julia .github/workflows/tasklayout/memlayout.jl
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'src/memlayout'
          author_name: GitHub Actions
